echo "We are trying this practical from linux EC2"
echo "We are from batch-33 and learning git/gihub"
echo "We are learning Branching"
echo "I am learning Git"
echo "I am learning Github"
echo "I am learning git on ubuntu os"
echo "Hello welcome to github"
echo "I am here to learn github"
echo "I am practicing github webhook"
echo "Hiiiii"
echo "I am working on webhook"
echo "hello hi"
